### ISSUE TITLE
Add to fossa example projects?

### ISSUE THREAD

**Issue by jssblck** [jmickelin/multi-home-cabal-example#1]
Hey @jmickelin! Thanks for [your PR](https://github.com/fossas/fossa-cli/pull/909), which was merged via [this PR](https://github.com/fossas/fossa-cli/pull/910) today!

We maintain example projects in this repository: https://github.com/fossas/example-projects/

Would you mind if I add this project as an example case to that repo? Alternately, feel free to make a PR to add it yourself.
I mostly ask because this repo isn't explicitly licensed, so I don't want to just copy it without a go-ahead from you.

Thanks!

**Comment by jmickelin** [comment]
Absolutely, go ahead and add it :)

Happy to help!

**Comment by jssblck** [comment]
Thanks!
